# Generated by Django 5.2 on 2025-12-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Полное название конференции или мероприятия', max_length=200, verbose_name='Название конференции')),
                ('description', models.TextField(help_text='Подробное описание конференции', verbose_name='Описание')),
                ('short_description', models.CharField(blank=True, help_text='Краткое описание для карточек и списков', max_length=500, verbose_name='Краткое описание')),
                ('start_date', models.DateTimeField(help_text='Дата и время начала конференции', verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(help_text='Дата и время окончания конференции', verbose_name='Дата окончания')),
                ('location', models.CharField(help_text='Адрес или место проведения конференции', max_length=200, verbose_name='Место проведения')),
                ('is_online', models.BooleanField(default=False, help_text='Отметьте, если конференция проводится онлайн', verbose_name='Онлайн мероприятие')),
                ('online_link', models.URLField(blank=True, help_text='Ссылка для подключения к онлайн конференции', null=True, verbose_name='Ссылка для онлайн участия')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('ongoing', 'В процессе'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='planned', help_text='Текущий статус конференции', max_length=20, verbose_name='Статус')),
                ('registration_deadline', models.DateTimeField(blank=True, help_text='Последний срок для регистрации участников', null=True, verbose_name='Срок регистрации')),
                ('max_participants', models.PositiveIntegerField(blank=True, help_text='Максимальное количество участников (если ограничено)', null=True, verbose_name='Максимальное количество участников')),
                ('organizer_name', models.CharField(blank=True, help_text='Название организации-организатора', max_length=200, verbose_name='Организатор')),
                ('contact_email', models.EmailField(blank=True, help_text='Email для связи с организаторами', max_length=254, verbose_name='Контактный email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Конференция',
                'verbose_name_plural': 'Конференции',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['start_date'], name='app_confere_start_d_0a0d9c_idx'), models.Index(fields=['status'], name='app_confere_status_e25b34_idx')],
            },
        ),
    ]
