# Generated by Django 5.2.2 on 2025-12-05 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='end_date',
        ),
        migrations.AddField(
            model_name='conference',
            name='curator',
            field=models.ForeignKey(blank=True, help_text='Пользователь-куратор, создавший данное мероприятие', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curated_conferences', to=settings.AUTH_USER_MODEL, verbose_name='Куратор'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='status',
            field=models.CharField(choices=[('not_started', 'Не началась'), ('completed', 'Завершена')], default='not_started', help_text='Текущий статус конференции', max_length=20, verbose_name='Статус'),
        ),
    ]
