# Generated by Django 5.2 on 2025-12-05 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_eventregistration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя отправителя', max_length=200, verbose_name='Имя')),
                ('email', models.EmailField(help_text='Email адрес для обратной связи', max_length=254, verbose_name='Email')),
                ('subject', models.CharField(help_text='Тема сообщения', max_length=200, verbose_name='Тема')),
                ('message', models.TextField(help_text='Текст сообщения', verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('read', 'Прочитано'), ('replied', 'Отвечено')], default='new', help_text='Статус обработки сообщения', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(blank=True, help_text='Пользователь, отправивший сообщение (если авторизован)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сообщение обратной связи',
                'verbose_name_plural': 'Сообщения обратной связи',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='app_contact_status_57cb0a_idx'), models.Index(fields=['created_at'], name='app_contact_created_22b6ff_idx')],
            },
        ),
    ]
